import { Inter } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "./socketcontext";
import { GlobalStateProvider } from "./globalcontext";
// import { WebRTCProvider } from "./webrtcContext"; // Import the WebRTC context

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStateProvider>
          <SocketProvider>
            {" "}
            {/* Wrap with WebRTCProvider */}
            {children}
          </SocketProvider>
        </GlobalStateProvider>
      </body>
    </html>
  );
}
