/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/sxAojF6v0m5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Syne } from 'next/font/google'
import { Gabarito } from 'next/font/google'

syne({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import Link from "next/link"

export function sharecomponent() {
  return (
    (<div className="flex flex-col min-h-screen bg-background text-foreground">
      <main className="flex-1 px-4 py-8 sm:px-6">
        <div className="mx-auto max-w-2xl">
          <div
            className="mb-6 rounded-md bg-muted p-4 text-center text-sm text-muted-foreground">
            Your text has been shared successfully. The link has been copied to your clipboard.
          </div>
          <Tabs defaultValue="share-text" className="w-full">
            <TabsList className="mb-4 flex w-full justify-between rounded-md bg-muted p-1">
              <TabsTrigger value="share-text">Share Text</TabsTrigger>
              <TabsTrigger value="share-password">Share Password</TabsTrigger>
              <TabsTrigger value="share-files">Share Files</TabsTrigger>
              <TabsTrigger value="share-folders">Share Folders</TabsTrigger>
            </TabsList>
            <TabsContent value="share-text" className="space-y-4">
              <Textarea placeholder="Enter your text to share" className="h-32 resize-none" />
              <Button>Share Text</Button>
            </TabsContent>
            <TabsContent value="share-password">
              <div className="space-y-4">
                <Input
                  type="password"
                  placeholder="Enter your password to share"
                  className="h-10" />
                <Button>Share Password</Button>
              </div>
            </TabsContent>
            <TabsContent value="share-files">
              <div className="space-y-4">
                <div
                  className="group relative flex h-32 items-center justify-center rounded-md border-2 border-dashed border-muted-foreground/50 transition-colors hover:border-muted-foreground">
                  <div
                    className="z-10 flex flex-col items-center justify-center gap-2 text-center text-muted-foreground">
                    <UploadIcon className="h-8 w-8" />
                    <p>Drag and drop files here</p>
                    <p className="text-sm">or click to upload</p>
                  </div>
                  <input
                    type="file"
                    multiple
                    className="absolute inset-0 z-20 h-full w-full cursor-pointer opacity-0" />
                </div>
                <Button>Share Files</Button>
              </div>
            </TabsContent>
            <TabsContent value="share-folders">
              <div className="space-y-4">
                <div
                  className="group relative flex h-32 items-center justify-center rounded-md border-2 border-dashed border-muted-foreground/50 transition-colors hover:border-muted-foreground">
                  <div
                    className="z-10 flex flex-col items-center justify-center gap-2 text-center text-muted-foreground">
                    <FolderIcon className="h-8 w-8" />
                    <p>Drag and drop folders here</p>
                    <p className="text-sm">or click to upload</p>
                  </div>
                  <input
                    type="file"
                    multiple
                    directory=""
                    webkitdirectory=""
                    className="absolute inset-0 z-20 h-full w-full cursor-pointer opacity-0" />
                </div>
                <Button>Share Folders</Button>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </main>
      <footer className="bg-muted px-4 py-6 sm:px-6">
        <div className="mx-auto max-w-2xl space-y-4">
          <div className="flex items-center justify-between">
            <p className="text-sm text-muted-foreground">Access your shared content:</p>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" className="h-8 gap-1 text-sm">
                <LinkIcon className="h-4 w-4" />
                <span>Copy Link</span>
              </Button>
              <Button variant="outline" size="sm" className="h-8 gap-1 text-sm">
                <CodeIcon className="h-4 w-4" />
                <span>Copy Code</span>
              </Button>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <Button variant="outline" size="sm" className="h-8 gap-1 text-sm">
              <UnplugIcon className="h-4 w-4" />
              <span>Disconnect</span>
            </Button>
            <Link
              href="#"
              className="inline-flex h-8 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}>
              Back to Home
            </Link>
          </div>
        </div>
      </footer>
    </div>)
  );
}

function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}


function FolderIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </svg>)
  );
}


function LinkIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>)
  );
}


function UnplugIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m19 5 3-3" />
      <path d="m2 22 3-3" />
      <path d="M6.3 20.3a2.4 2.4 0 0 0 3.4 0L12 18l-6-6-2.3 2.3a2.4 2.4 0 0 0 0 3.4Z" />
      <path d="M7.5 13.5 10 11" />
      <path d="M10.5 16.5 13 14" />
      <path d="m12 6 6 6 2.3-2.3a2.4 2.4 0 0 0 0-3.4l-2.6-2.6a2.4 2.4 0 0 0-3.4 0Z" />
    </svg>)
  );
}


function UploadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>)
  );
}
